# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V66CFwntK5js_P8PxCXAL9jFfHN38pkH
"""

import seaborn as sns

titan =sns.load_dataset('titanic')

import plotly.graph_objects as go

fig= go.Figure()
fig.add_trace(go.Scatter(x=titan.age, y= titan.fare, mode= 'markers'))
fig.show()

tips= sns.load_dataset('tips')

tips.head()

import plotly.express as px
 
df = px.data.tips()
 
fig = px.box(df, x = "sex", y="total_bill")
fig.show()

import plotly.graph_objects as go
fig= go.Figure(data=[go.Histogram(x= tips.sex, y= tips.total_bill)])
fig.show()

import plotly.express as px
  
df = px.data.tips()
  
c

import plotly.express as px

df= px.data.iris()

df

fig = px.scatter_matrix(df,  dimensions=["sepal_length", "sepal_width", "petal_length", "petal_width"], color="species")
fig.show()

import plotly.express as px
df = px.data.tips()
fig = px.histogram(df, x="total_bill", y="tip", color="sex", marginal="rug",
                   hover_data=df.columns)
fig.show()

